// <auto-generated />
using System;
using GoldPrice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldPrice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251005181849_UpdateModel_2025")]
    partial class UpdateModel_2025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoldPrice.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RecordStatus")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Address = "1 Nguyễn Huệ, Q1, TP.HCM",
                            CompanyName = "Công ty Vàng SJC",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@sjc.com.vn",
                            IsDefault = false,
                            IsDeleted = false,
                            ModifiedBy = "admin",
                            ModifiedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "02723889110",
                            RecordStatus = "Active",
                            TaxCode = "0301234567",
                            Website = "https://sjc.com.vn"
                        });
                });

            modelBuilder.Entity("GoldPrice.Models.GoldPrice", b =>
                {
                    b.Property<int>("GoldPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoldPriceId"));

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("money");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoldTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBuyUpdating")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSellUpdating")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordStatus")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("money");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("GoldPriceId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GoldTypeId");

                    b.ToTable("GoldPrices");

                    b.HasData(
                        new
                        {
                            GoldPriceId = 1,
                            ApplyDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BuyPrice = 7800000m,
                            CompanyId = 1,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoldTypeId = 1,
                            IsBuyUpdating = false,
                            IsDeleted = false,
                            IsSellUpdating = false,
                            ModifiedBy = "admin",
                            ModifiedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordStatus = "Active",
                            SellPrice = 7850000m,
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("GoldPrice.Models.GoldPriceLog", b =>
                {
                    b.Property<int>("GoldPriceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoldPriceLogId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoldPriceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NewBuyPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("NewSellPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("OldBuyPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("OldSellPrice")
                        .HasColumnType("money");

                    b.Property<string>("RecordStatus")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("GoldPriceLogId");

                    b.ToTable("GoldPriceLogs");
                });

            modelBuilder.Entity("GoldPrice.Models.GoldType", b =>
                {
                    b.Property<int>("GoldTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoldTypeId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoldTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordStatus")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("GoldTypeId");

                    b.ToTable("GoldTypes");

                    b.HasData(
                        new
                        {
                            GoldTypeId = 1,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoldTypeName = "SJC 9999",
                            IsDeleted = false,
                            ModifiedBy = "admin",
                            ModifiedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordStatus = "Active"
                        },
                        new
                        {
                            GoldTypeId = 2,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoldTypeName = "PNJ 24K",
                            IsDeleted = false,
                            ModifiedBy = "admin",
                            ModifiedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordStatus = "Active"
                        },
                        new
                        {
                            GoldTypeId = 3,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoldTypeName = "DOJI 18K",
                            IsDeleted = false,
                            ModifiedBy = "admin",
                            ModifiedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecordStatus = "Active"
                        });
                });

            modelBuilder.Entity("GoldPrice.Models.GoldPrice", b =>
                {
                    b.HasOne("GoldPrice.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldPrice.Models.GoldType", "GoldType")
                        .WithMany("GoldPrices")
                        .HasForeignKey("GoldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("GoldType");
                });

            modelBuilder.Entity("GoldPrice.Models.GoldType", b =>
                {
                    b.Navigation("GoldPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
